### ISSUE TITLE
Block placer crashing server

### ISSUE THREAD

**Issue by Spaig** [UniversalLP/VanillaAutomation#27]
Hello!

Whenever we have the block placer place a block on our server, it crashes with this message:

Description: Exception while ticking a block

java.lang.NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503_a()Lnet/minecraft/util/ResourceLocation;
	at de.universallp.va.core.block.BlockPlacer.placeBlock(BlockPlacer.java:90)
	at de.universallp.va.core.block.BlockPlacer.func_180650_b(BlockPlacer.java:152)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:736)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Please advise :)

**Comment by univrsal** [comment]
I need a little more info. What version of Minecraft and what version of VanillaAutomation are you using?

**Comment by Spaig** [comment]
Right, duh, sorry. We're on minecraft 1.12.2 and VA version 1.12-1.4.

**Comment by univrsal** [comment]
Alright so the latest version. I'll try my best to fix this as soon as possible

**Comment by univrsal** [comment]
Fixed with e507cd004dae41771396a2ed79027bbe5d14dc41 @univrsal univrsal committed a minute ago 
I'll make a release later, thanks for reporting!
