### ISSUE TITLE
Game crashes when you right click the Auto Trader

### ISSUE THREAD

**Issue by Lothrazar** [UniversalLP/VanillaAutomation#4]
Not sure what this block does, but i just placed it and clicked it and my game closed. I was in creative mode just testing

Log:

ld tconstruct:seared_stairs_stone
[23:28:33] [Server thread/INFO] [FML]: Applying holder lookups
[23:28:33] [Server thread/INFO] [FML]: Holder lookups applied
[23:28:33] [Server thread/INFO] [FML]: Loading dimension 0 (Kingdoms) (net.minecraft.server.integrated.IntegratedServer@1a1bb8da)
[23:28:34] [Server thread/INFO] [FML]: Loading dimension 1 (Kingdoms) (net.minecraft.server.integrated.IntegratedServer@1a1bb8da)
[23:28:34] [Server thread/INFO] [FML]: Loading dimension -1 (Kingdoms) (net.minecraft.server.integrated.IntegratedServer@1a1bb8da)
[23:28:34] [Server thread/INFO]: Preparing start region for level 0
[23:28:35] [Server thread/INFO]: Preparing spawn area: 0%
[23:28:36] [Server thread/INFO]: Preparing spawn area: 37%
[23:28:37] [Server thread/INFO]: Preparing spawn area: 88%
[23:28:38] [Server thread/INFO] [SimilsaxTranstructors]: Syncing Server configs
[23:28:39] [Server thread/INFO]: Changing view distance to 6, from 10
[23:28:40] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[23:28:40] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[23:28:40] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 69 mods : tombmanygraves@1.9.4_1.10.2-2.1.8,inventorysorter@0.10.0+42,ExtraUtils2@1.0,disenchanter@1.4,netherportalfix@1.0,lteleporters@1.1.3,SimilsaxTranstructors@1.10.2.18,randomore@1.3.0,samsocean@1.0.0,kleeslabs@3.3.5,PersistentBits@1.0.4,Stackie@1.6.0.44,mcp@9.19,exp@1.1,furnus@1.83,journeymap@1.10.2-5.2.4,powerinventory@2.3.0,storagenetwork@1.12.8,HoloInventory@2.0.2.136,endercrop@1.9-1.2-1836,underphangables@1.0.2,betterbuilderswands@0.6.5,grapple_hooks@1.0.8,va@1.10.2-1.3,giacomostravelogue@1.01,LunatriusCore@1.1.2.36,vc@v1.0.2b-mc1.10.2,endercompass@1.2.3.2,jeresources@0.4.9.50,supercraftingframe@1.2.1.87,ExtraRails@1.1.1,malisisdoors@1.9.4-5.0.3,Quark@r1.0-53,cyclicmagic@1.6.3,Ding@MC1.9.0v2,malisiscore@1.9.4-4.1.1,VeinMinerModSupport@0.34.1_1.9-73be663,mousetweaks@2.6.4,claybucket@1.1,Forge@12.18.1.2069,torchpl@1.1,Chameleon@1.10-2.1.7,ChunkAnimator@1.2,SophisticatedWolves@3.6.1,VeinMiner@0.34.1_1.9-73be663,oreplants@0.0.28,samsapples@1.1.5,StorageDrawers@1.10.2-3.2.6,forgecreeperheal@1.3.0,MineTweaker3@3.0.10,shadowmc@3.4.4,AppleCore@2.0.0,backpacks16840@3.1.1,HungerInPeace@1.0.0,FML@8.0.99.99,GlobalGameRules@1.0,fishing@1.4.3,appleskin@1.0.2,arrowcammod@2.2.0,anvils@1.2.2.0,JEI@3.9.0.246,cs@1.0.2,mineTunes@1.2-9,AutoRegLib@1.0-1,Schematica@1.7.8.151,extraalchemy@0.2.8.1-beta,soundfilters@0.9_for_1.9,BuildersGuides@1.10.2-1.0.2,SparksHammers@1.10.2-1.0
[23:28:40] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[23:28:40] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[23:28:40] [Server thread/INFO]: Lothrazar[local:E:c439b7e2] logged in with entity id 283 at (-226.5888941367403, 57.0, 184.3559660047949)
[23:28:40] [Server thread/INFO]: Lothrazar has joined the game
[23:28:43] [Server thread/INFO]: Saving and pausing game...
[23:28:43] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/Overworld
[23:28:43] [Client thread/INFO] [JEI]: Registering plugin: mezz.jei.plugins.vanilla.VanillaPlugin
[23:28:43] [Client thread/INFO] [JEI]: Registered  plugin: mezz.jei.plugins.vanilla.VanillaPlugin in 0 seconds
[23:28:43] [Client thread/INFO] [JEI]: Registering plugin: mrriegel.storagenetwork.jei.SNPlugin
[23:28:43] [Client thread/INFO] [JEI]: Registered  plugin: mrriegel.storagenetwork.jei.SNPlugin in 0 seconds
[23:28:43] [Client thread/INFO] [JEI]: Registering plugin: mrriegel.furnus.jei.PulvusJEIPlugin
[23:28:43] [Client thread/INFO] [JEI]: Registered  plugin: mrriegel.furnus.jei.PulvusJEIPlugin in 0 seconds
[23:28:43] [Client thread/INFO] [JEI]: Registering plugin: de.universallp.va.client.jei.JEIPlugin
[23:28:43] [Client thread/INFO] [JEI]: Registered  plugin: de.universallp.va.client.jei.JEIPlugin in 0 seconds
[23:28:43] [Client thread/INFO] [JEI]: Registering plugin: jeresources.jei.JEIConfig
[23:28:44] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/Nether
[23:28:44] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/The End
[23:28:44] [Client thread/INFO] [JEI]: Registered  plugin: jeresources.jei.JEIConfig in 0 seconds
[23:28:44] [Client thread/INFO] [JEI]: Registering plugin: zabi.minecraft.extraalchemy.integration.jei.JeiPlugin
[23:28:44] [Client thread/INFO] [JEI]: Registered  plugin: zabi.minecraft.extraalchemy.integration.jei.JeiPlugin in 0 seconds
[23:28:44] [Client thread/INFO] [JEI]: Registering plugin: io.github.danielm59.oreplants.jei.JeiPlugin
[23:28:44] [Client thread/INFO] [JEI]: Registered  plugin: io.github.danielm59.oreplants.jei.JeiPlugin in 0 seconds
[23:28:44] [Client thread/INFO] [JEI]: Registering plugin: minetweaker.mods.jei.JEIAddonPlugin
[23:28:44] [Client thread/INFO] [JEI]: Registered  plugin: minetweaker.mods.jei.JEIAddonPlugin in 0 seconds
[23:28:44] [Client thread/INFO] [JEI]: Registering plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin
[23:28:45] [Client thread/INFO] [JEI]: Registered  plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin in 0 seconds
[23:28:45] [Client thread/INFO] [JEI]: Registering plugin: com.brightspark.sparkshammers.integration.jei.SparksHammersPlugin
[23:28:45] [Client thread/INFO] [JEI]: Registered  plugin: com.brightspark.sparkshammers.integration.jei.SparksHammersPlugin in 0 seconds
[23:28:45] [Client thread/INFO] [JEI]: Registering plugin: com.m4thg33k.tombmanygraves.JEIIntegration.TombManyGravesPlugin
[23:28:45] [Client thread/INFO] [JEI]: Registered  plugin: com.m4thg33k.tombmanygraves.JEIIntegration.TombManyGravesPlugin in 0 seconds
[23:28:45] [Client thread/INFO] [JEI]: Registering plugin: net.shadowfacts.extrarails.compat.ERJEIPlugin
[23:28:45] [Client thread/INFO] [JEI]: Registered  plugin: net.shadowfacts.extrarails.compat.ERJEIPlugin in 0 seconds
[23:28:45] [Client thread/INFO] [JEI]: Registering plugin: mezz.jei.plugins.jei.JEIInternalPlugin
[23:28:45] [Client thread/INFO] [JEI]: Registered  plugin: mezz.jei.plugins.jei.JEIInternalPlugin in 0 seconds
[23:28:48] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2173ms behind, skipping 43 tick(s)
[23:28:49] [Client thread/INFO] [SimilsaxTranstructors]: Syncing Client configs
[23:28:50] [Client thread/INFO]: [CHAT] Veinminer using client keybind. See mod config for details.
[23:28:50] [Client thread/INFO] [VeinMiner]: Received mode change 1
[23:28:50] [Client thread/INFO]: [CHAT] Veinminer client keybind set to activate on pressing the key.
[23:28:52] [Client thread/INFO] [journeymap]: Loading journeymap.topo.config
[23:28:53] [Client thread/INFO] [journeymap]: Loaded 0 waypoints from C:\Users\lothr\OneDrive\Documents\Curse\Minecraft\Instances\Overpowered Non Content (1)\journeymap\data\sp\Kingdoms\waypoints
[23:28:53] [Client thread/INFO] [journeymap]: Blocks and textures are current
[23:28:53] [Client thread/INFO] [journeymap]: Mapping started in C:\Users\lothr\OneDrive\Documents\Curse\Minecraft\Instances\Overpowered Non Content (1)\journeymap\data\sp\Kingdoms\DIM0. Memory: 1971MB total, 1014MB free 
[23:28:53] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[23:28:53] [Client thread/INFO] [journeymap]: JourneyMap: Press [J]
[23:29:25] [Netty Local Client IO #0/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -1
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:407) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:273) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [LocalChannel$5.class:4.0.23.Final]
    at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33) [LocalEventLoop.class:4.0.23.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at de.universallp.va.core.network.messages.MessageSetFieldClient.fromBytes(MessageSetFieldClient.java:71) ~[MessageSetFieldClient.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
    ... 24 more
[23:29:25] [Netty Local Client IO #0/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -1
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:407) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:273) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [LocalChannel$5.class:4.0.23.Final]
    at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33) [LocalEventLoop.class:4.0.23.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at de.universallp.va.core.network.messages.MessageSetFieldClient.fromBytes(MessageSetFieldClient.java:71) ~[MessageSetFieldClient.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
    ... 24 more
[23:29:25] [Netty Local Client IO #0/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -1
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:407) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:273) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [LocalChannel$5.class:4.0.23.Final]
    at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33) [LocalEventLoop.class:4.0.23.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at de.universallp.va.core.network.messages.MessageSetFieldClient.fromBytes(MessageSetFieldClient.java:71) ~[MessageSetFieldClient.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
    ... 24 more
[23:29:25] [Netty Local Client IO #0/ERROR] [FML]: There was a critical exception handling a packet on channel va
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -1
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:407) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:273) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [LocalChannel.class:4.0.23.Final]
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [LocalChannel$5.class:4.0.23.Final]
    at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33) [LocalEventLoop.class:4.0.23.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at de.universallp.va.core.network.messages.MessageSetFieldClient.fromBytes(MessageSetFieldClient.java:71) ~[MessageSetFieldClient.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
    at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.0.23.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
    ... 24 more
[23:29:25] [Netty Local Client IO #0/INFO] [Schematica]: Scheduling client settings reset.
[23:29:25] [Server thread/INFO]: Lothrazar lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[23:29:25] [Server thread/INFO]: Lothrazar has left the game
[23:29:25] [Client thread/INFO] [journeymap]: Mapping halted in C:\Users\lothr\OneDrive\Documents\Curse\Minecraft\Instances\Overpowered Non Content (1)\journeymap\data\sp\Kingdoms\DIM0
[23:29:25] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:29:25] [Server thread/INFO]: Stopping server
[23:29:25] [Server thread/INFO]: Saving players
[23:29:25] [Server thread/INFO]: Saving worlds
[23:29:25] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/Overworld
[23:29:25] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/Nether
[23:29:25] [Server thread/INFO]: Saving chunks for level 'Kingdoms'/The End
[23:29:25] [Server thread/INFO] [FML]: Unloading dimension 0
[23:29:25] [Server thread/INFO] [FML]: Unloading dimension -1
[23:29:25] [Server thread/INFO] [FML]: Unloading dimension 1
[23:29:26] [Server thread/INFO] [FML]: Applying holder lookups
[23:29:26] [Server thread/INFO] [FML]: Holder lookups applied

**Comment by univrsal** [comment]
Yeah it's not a finished block, that's why it's not craftable right now.
It's supposed to be able to trade with villagers automatically, when I finish it... soonish :D
Edit: Well turns out the block wasn't that good of an idea, so I removed it.
